### ISSUE TITLE
Instructions for installation

### ISSUE THREAD

**Issue by musiphil** [rhysd/conflict-marker.vim#1]
It would be nice to have a section on installation in README.

**Comment by rhysd** [comment]
There is no special process to install this plugin.  You can install this by the same way as the other plugins.  But there seems to be no reason not to add installation instruction.  I'll do that and close this issue after.

Note that almost all user install plugins via plugin manager.  So following their instruction is better.

**Comment by musiphil** [comment]
Thanks for the update.
The instruction omits `autoload/conflict_marker/detect.vim`, though.

**Comment by rhysd** [comment]
@musiphil 

Thanks for pointing out.  I fixed.
