### ISSUE TITLE
Enhancement: Adopt both in reverse order

### ISSUE THREAD

**Issue by ruifm** [rhysd/conflict-marker.vim#15]
### Adopt Both in reverse order

```
<<<<<<< HEAD
ours
=======
theirs
>>>>>>> deadbeef0123
```

↓`cB` or `:ConflictMarkerBoth!`

```
theirs
ours
```

I think the mappings `cB` and the banged command `:ConflictMarkerBoth!` actually fit well for this usecase.

**Comment by rhysd** [comment]
Thank you for the suggestion. It looks useful and reasonable.
