### ISSUE TITLE
Support for Parent

### ISSUE THREAD

**Issue by spf13** [rhysd/conflict-marker.vim#2]
A feature of git is that it can also create conflict markers for the parent. These are very useful, but unfortunately not supported by conflict-marker.vim yet.

**Comment by rhysd** [comment]
Hi @spf13 ,

Thank you for your pointing out. I don't know the feature... Could you tell me which command (and option) I can use the feature with?

**Comment by rhysd** [comment]
Are you saying about 3-way merging (target/marge-base/HEAD)?

**Comment by spf13** [comment]
what happens when you set:
`git config merge.conflictstyle diff3`

**Comment by rhysd** [comment]
Thanks, I'll try

**Comment by keysmashes** [comment]
I have made a [diff3 branch](https://github.com/anowlcalledjosh/conflict-marker.vim/tree/diff3) on my GitHub fork that supports the diff3 format. It doesn't have any tests (and probably the tests are now broken), and it *only* supports the diff3 format – if you open a file with default conflict markers, it will not recognise them – but it works well enough for me.

Hopefully I will have time at some point to make the format configurable and open a pull request.

**Comment by rhysd** [comment]
This was fixed by #13. Thank you @ryuta69 for sending the patch.
