### ISSUE TITLE
Support conflictStyle = diff3

### ISSUE THREAD

**Issue by unphased** [rhysd/conflict-marker.vim#5]
I like this style of conflict markers because it provides me enough data to both as a human and programmatically see exactly what THEIR change is and OUR change is. 

Git conflicts provide chunks that are way easier to grok as diffs themselves. Using this config allows this to be possible.

So at any rate, in the presence of this git config, this plugin fails to account for the `|||||||` section.

**Comment by keysmashes** [comment]
seems to be the same as #2

**Comment by unphased** [comment]
Thank you, @anowlcalledjosh ! I will specify your branch in my vim-plug and report back once I test it.
